---

- hosts: all
  become: true
  tasks:

    - name: Update repository index
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Install apache2 package
      ansible.builtin.apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "24.04"

    - name: Add php support for apache
      ansible.builtin.apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Update repository index
      ansible.builtin.dnf:
        update_cache: yes
      when: ansible_distribution == "Fedora"

    - name: Install httpd (equals apache) package
      ansible.builtin.dnf:
        name: httpd
        state: latest
      when: ansible_distribution == "Fedora"

    - name: Add php support for apache
      ansible.builtin.dnf:
        name: php
        state: latest
      when: ansible_distribution == "Fedora"
